# Generated by Django 4.0.6 on 2024-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_weeklystatusreport_efforts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystatusreport',
            name='percentage_complete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
