# Generated by Django 4.0.6 on 2024-05-15 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0005_remove_testcasesteps_step_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort_date', models.DateField(default=datetime.date.today)),
                ('spend_hr', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('assgined_to', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
                ('bug_obj', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.bug', verbose_name='Bug_id')),
            ],
        ),
    ]
