# Generated by Django 4.0.6 on 2024-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0007_alter_bug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugeffort',
            name='effor_status',
            field=models.CharField(blank=True, choices=[('NOTSTARTED', 'NOT-STARTED'), ('INPROGRESS', 'IN-PROGRESS'), ('FIXED', 'FIXED'), ('HOLD', 'HOLD'), ('OPEN', 'OPEN'), ('REOPEN', 'REOPEN'), ('CLOSE', 'CLOSE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='comment',
            field=models.CharField(blank=True, default='NA', max_length=500, null=True),
        ),
    ]
