# Generated by Django 4.0.6 on 2024-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0009_bug_bug_score_bugeffort_percentage_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugeffort',
            name='spend_hr',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=100, null=True),
        ),
    ]
